# Generated by Django 4.2.3 on 2023-10-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=100)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('info_about_author', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('year_publish', models.IntegerField(default=0)),
                ('short_info', models.TextField(max_length=2000)),
                ('image_book', models.ImageField(upload_to='media/images/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainlibsite.author')),
            ],
            options={
                'verbose_name': 'Список книг',
                'verbose_name_plural': 'Список книг',
                'ordering': ['name', 'author'],
            },
        ),
    ]
