# Generated by Django 4.2.3 on 2023-10-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlibsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='info_about_author',
            field=models.TextField(max_length=1000),
        ),
    ]
